version: '2'
services:
    training:
        image: sphereio/commercetools-php-training
        volumes:
            - .:/opt/app
        working_dir: /opt/app
        container_name: application
        env_file:
          - parameters.env
        command: vendor/bin/phpunit
